import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import styles from '../styles/Home.module.css'
import {useEffect, useState} from "react";
import AddUserPop from "../../components/AddUserPop";
import EditRole from "../../components/EditRolePop";


export default function AdminPage() {

    const [addUserPopShown, setAddUserPopShown] = useState(false)
    const toggleAddUserPop = () => {
        setAddUserPopShown(!addUserPopShown)
    }

    const [editRolePopShown, setEditRolePopShown] = useState(false)
    const toggleEditRolePop = () => {
        setEditRolePopShown(!editRolePopShown)
    }



    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={'bg-white min-h-screen'}>
                <div className={'w-full h-12 bg-blue grid items-center grid-cols-12'}>
                    <button
                        className={'font-verdana p-2 h-full flex items-center justify-center hover:bg-orange text-white font-bold col-span-1 cursor-pointer hover:bg-orange'}
                        onClick={() => {
                            toggleAddUserPop()
                        }}>Add user
                    </button>
                    <button
                        className={'font-verdana p-2 h-full flex items-center justify-center hover:bg-orange text-white font-bold col-span-1 cursor-pointer hover:bg-orange'}>Exit
                    </button>
                    <img className={'col-start-12 p-2 h-full'} src={'/images/logo_base_307x92.png'}/>
                </div>
                <div className={'w-full p-3'}>
                    <div className={'flex items-center'}>
                        <p className={'mr-4'}>Office: </p>
                        <select
                            className={'h-8 w-48 focus-visible:border-blue focus:border-2 focus:border-blue border-2 border-blue'}>
                            <option>Moscow</option>
                            <option>Berlin</option>
                            <option>Kyiv</option>
                        </select>
                    </div>
                    <div className={'w-full mt-5 flex flex-col border-blue border-2'}>
                        <div className={'grid grid-cols-6 '}>
                            <div className={'border-r-2 bg-blue text-white p-2'}>Name</div>
                            <div className={'border-r-2 bg-blue text-white p-2'}>Last name</div>
                            <div className={'border-r-2 bg-blue text-white p-2'}>Age</div>
                            <div className={'border-r-2 bg-blue text-white p-2'}>User role</div>
                            <div className={'border-r-2 bg-blue text-white p-2'}>Email address</div>
                            <div className={'border-r-2 bg-blue text-white p-2'}>Office</div>
                        </div>
                        <div className={'grid grid-cols-6 border-b-2 border-blue '}>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-blue p-2'}>Name</div>
                        </div>
                        <div className={'grid grid-cols-6 border-b-2 border-blue '}>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-blue p-2'}>Name</div>
                        </div>
                        <div className={'grid grid-cols-6 border-b-2 border-blue '}>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-blue p-2'}>Name</div>
                        </div>
                        <div className={'grid grid-cols-6 border-b-2 border-blue '}>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-blue p-2'}>Name</div>
                        </div>
                        <div className={'grid grid-cols-6 border-b-2 border-blue '}>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-blue p-2'}>Name</div>
                        </div>
                        <div className={'grid grid-cols-6 border-b-2 border-blue '}>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-blue p-2'}>Name</div>
                        </div>
                        <div className={'grid grid-cols-6 border-b-2 border-blue '}>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-blue p-2'}>Name</div>
                        </div>
                        <div className={'grid grid-cols-6 border-b-2 border-blue '}>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-blue p-2'}>Name</div>
                        </div>
                        <div className={'grid grid-cols-6 border-b-2 border-blue '}>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-r-2 border-blue  p-2'}>Name</div>
                            <div className={'border-blue p-2'}>Name</div>
                        </div>
                    </div>
                    <div className={'flex mt-5 items-center'}>
                        <button
                            className={'bg-orange mr-32 p-2 flex items-center justify-center font-verdana font-bold text-white'} onClick={()=>{toggleEditRolePop()}}>Change
                            role
                        </button>
                        <button
                            className={'bg-orange p-2 flex items-center justify-center font-verdana font-bold text-white'}>Enable
                            / Disable login
                        </button>
                    </div>
                </div>
                {addUserPopShown ? <div className={'fixed z-20 top-0 left-0 w-screen h-screen'}>
                    <AddUserPop togglePop={toggleAddUserPop}></AddUserPop>
                </div> : null}
                {editRolePopShown ? <div className={'fixed z-20 top-0 left-0 w-screen h-screen'}>
                    <EditRole togglePop={toggleEditRolePop}></EditRole>
                </div> : null}


            </main>
        </>
    )
}
